name: yolov8n_ms
channels: [conda-forge, defaults]
dependencies:
  - python=3.9
  - pip
  - numpy
  - pillow
  - tqdm
  - pyyaml
  - matplotlib
  - pip:
      - opencv-python
      - pycocotools
      # MindSpore should be installed separately according to CPU/GPU/Ascend backend.
